# Generated by Django 3.2.9 on 2021-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_music_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='namePlaylist',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
