# Generated by Django 3.1.3 on 2021-11-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_playlist_nameplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='musicas',
        ),
        migrations.AddField(
            model_name='playlist',
            name='musicas',
            field=models.ManyToManyField(to='App.Music'),
        ),
    ]
