# Generated by Django 3.1.3 on 2021-11-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20211104_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='musicas',
            field=models.ManyToManyField(blank=True, to='App.Music'),
        ),
    ]
